# Generated by Django 5.0.4 on 2024-05-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_user'),
        ('deals', '0003_deal_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='user',
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
