# Generated by Django 5.0.4 on 2024-05-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('deals', '0005_alter_deal_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.product', verbose_name='Продукт'),
        ),
        migrations.RemoveField(
            model_name='deal',
            name='unit_price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
