# Generated by Django 5.0.4 on 2024-05-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_user'),
        ('deals', '0007_deal_company_alter_deal_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='customers.customer'),
        ),
    ]
