# Generated by Django 5.0.4 on 2024-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(choices=[('OOO', 'ООО'), ('ИП', 'ИП'), ('Физическое лицо', 'Физическое лицо')], default='Физическое лицо', max_length=20, verbose_name='Организация'),
        ),
    ]
