# Generated by Django 5.0.4 on 2024-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.CharField(choices=[('ООО', 'ООО'), ('ИП', 'ИП'), ('Физическое лицо', 'Физическое лицо')], default='Физическое лицо', max_length=20, verbose_name='Организация'),
        ),
    ]
